export const CREATE_NEW_MULTI_SPECIFICATION = "CREATE_NEW_MULTI_SPECIFICATION";
export const RESET_MULTI_SPECIFICATION = "RESET_MULTI_SPECIFICATION";
export const REMOVE_MULTI_SPECIFICATION = "REMOVE_MULTI_SPECIFICATION";
export const ADD_TO_MULTI_SPECIFICATION = "ADD_TO_MULTI_SPECIFICATION";
export const DELETE_FROM_MULTI_SPECIFICATION = "DELETE_FROM_MULTI_SPECIFICATION";