export const CREATE_NEW_STANDARD_SPECIFICATION = "CREATE_NEW_STANDARD_SPECIFICATION";
export const RESET_STANDARD_SPECIFICATIONS = "RESET_SPECIFICATIONS";
export const REMOVE_STANDARD_SPECIFICATION = "REMOVE_SPECIFICATION";
export const UPDATE_FACET_STATE = "UPDATE_FACET_STATE";
export const ADD_TO_STANDARD_SPECIFICATION = "ADD_TO_SPECIFICATION";
export const DELETE_FROM_STANDARD_SPECIFICATION = "DELETE_FROM_SPECIFICATION";
