export const UPDATE_FACET_STATE = "UPDATE_FACET_STATE";
export const ADD_TO_SCHEMA = "ADD_TO_SCHEMA";
export const DELETE_FROM_SCHEMA = "DELETE_FROM_SCHEMA";
export const CHANGE_ACTIVE_SPECIFICATIONS = "CHANGE_ACTIVE_SPECIFICATIONS";
