export const CREATE_NEW_SPECIFICATION = "CREATE_NEW_SPECIFICATION";
export const CHANGE_ACTIVE_SPECIFICATIONS = "CHANGE_ACTIVE_SPECIFICATIONS";
export const DELETE_SPECIFICATION = "DELETE_SPECIFICATION"
