export const CREATE_NEW_SPECIFICATION = "CREATE_NEW_SPECIFICATION";
export const CHANGE_ACTIVE_SPECIFICATIONS = "CHANGE_ACTIVE_SPECIFICATIONS";
export const DELETE_SPECIFICATION = "DELETE_SPECIFICATION"

// export const CREATE_NEW_SPECIFICATION = "CREATE_NEW_SPECIFICATION";
// export const REMOVE_SPECIFICATION = "REMOVE_SPECIFICATION";
// export const SELECT_SPECIFICATION = "SELECT_SPECIFICATION";
// export const UPDATE_FACET_STATE = "UPDATE_FACET_STATE";
// export const ADD_TO_SPECIFICATION = "ADD_TO_SCHEMA";
// export const DELETE_FROM_SPECIFICATION = "DELETE_FROM_SCHEMA";
// export const CHANGE_ACTIVE_SPECIFICATIONS = "CHANGE_ACTIVE_SPECIFICATIONS";
// export const RESET_SPECIFICATIONS = "RESET_SPECIFICATIONS";
