export const FETCH_MODEL_MARGINAL_SUCCESS = "FETCH_MODEL_MARGINAL_SUCCESS";
export const FETCH_MODEL_MARGINAL_ERROR = "FETCH_MODEL_MARGINAL_ERROR";

export const FETCH_DATA_MARGINAL_SUCCESS = "FETCH_DATA_MARGINAL_SUCCESS";
export const FETCH_DATA_MARGINAL_ERROR = "FETCH_DATA_MARGINAL_ERROR";

export const FETCH_MODEL_DATA_SUCCESS = "FETCH_MODEL_DATA_SUCCESS";
export const FETCH_MODEL_DATA_ERROR = "FETCH_MODEL_DATA_ERROR";

export const FETCH_TRAINING_DATA_SUCCESS = "FETCH_TRAINING_DATA_SUCCESS";
export const FETCH_TRAINING_DATA_ERROR = "FETCH_TRAINING_DATA_ERROR";

export const FETCH_DATA_DENSITY_SUCCESS = "FETCH_DATA_DENSITY_SUCCESS";
export const FETCH_DATA_DENSITY_ERROR = "FETCH_DATA_DENSITY_ERROR";

export const FETCH_MODEL_DENSITY_SUCCESS = "FETCH_MODEL_DENSITY_SUCCESS";
export const FETCH_MODEL_DENSITY_ERROR = "FETCH_MODEL_DENSITY_ERROR";

export const INITIALIZE_NEW_STANDARD_PLOT = "INITIALIZE_NEW_STANDARD_PLOT";
export const DELETE_STANDARD_PLOT = "DELETE_STANDARD_PLOT";

export const FETCH_INITIAL_PLOTDATA_ERROR = "FETCH_INITIAL_PLOTDATA_ERROR";
export const FETCH_INITIAL_PLOTDATA_SUCCESS = "FETCH_INITIAL_PLOTDATA_SUCCESS";

export const FETCH_DATA_PENDING = "FETCH_DATA_PENDING";
