export const CREATE_NEW_PPC_SPECIFICATION = "CREATE_NEW_PPC_SPECIFICATION";
export const RESET_PPC_SPECIFICATION = "RESET_PPC_SPECIFICATION";
export const REMOVE_PPC_SPECIFICATION = "REMOVE_PPC_SPECIFICATION";
export const ADD_TO_PPC_SPECIFICATION = "ADD_TO_PPC_SPECIFICATION";
export const DELETE_FROM_PPC_SPECIFICATION = "DELETE_FROM_PPC_SPECIFICATION";
export const CHANGE_PPC_SPECIFICATION = "CHANGE_PPC_SPECIFICATION";