export const CREATE_NEW_PPC_PLOT = "CREATE_NEW_PPC_PLOT";
export const DELETE_PPC_PLOT = "DELETE_PPC_PLOT";
export const ADD_DATA_TO_PPC_PLOT = "ADD_DATA_TO_PPC_PLOT";
export const CHANGE_PPC_PLOT = "CHANGE_PPC_PLOT";