export const FETCH_PLOT_DATA = "FETCH_PLOT_DATA";
export const UPDATE_MULTI_PLOT_DATA = "UPDATE_MULTI_PLOT_DATA";
export const RESET_MULTI_PLOT_DATA = "RESET_MULTI_PLOT_DATA";
export const UPDATE_PLOT_LAYOUT = "UPDATE_PLOT_LAYOUT";
export const INITIALIZE_NEW_MULTI_PLOT = "INITIALIZE_NEW_MULTI_PLOT";
export const DELETE_MULTI_PLOT = "DELETE_MULTI_PLOT";
