export const CREATE_NEW_VISUALIZATION = "CREATE_NEW_VISUALIZATION";
export const CHANGE_ACTIVE_VISUALIZATION = "CHANGE_ACTIVE_VISUALIZATION";
export const FILL_VISUALIZATION = "FILL_VISUALIZATION";
export const DELETE_VISUALIZATION = "DELETE_VISUALIZATION";