export const CREATE_NEW_MODEL = "CREATE_NEW_MODEL";
export const SHOW_PCI_GRAPH = "SHOW_PCI_GRAPH";
export const HIDE_PCI_GRAPH = "HIDE_PCI_GRAPH";
export const DELETE_MODEL = "DELETE_MODEL";
export const UPDATE_MODEL_DIMENSIONS = "UPDATE_MODEL_DIMENSIONS";