export const INITIALIZE_NEW_PLOT_SETTINGS = "INITIALIZE_NEW_PLOT_SETTINGS";
export const DELETE_PLOT_SETTINGS = "DELETE_PLOT_SETTINGS";
export const UPDATE_PLOT_TITLE    = "UPDATE_PLOT_TITLE"
export const UPDATE_XLABEL        = "UPDATE_XLABEL"
export const UPDATE_YLABEL        = "UPDATE_YLABEL"