name: Tests

on:
  push:
    branches:
      - master
    # paths:
    #  - "src/*"
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Unittests
    runs-on: ubuntu-18.04
    matrix:
      node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Unittests with node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
