export const UPDATE_PLOT_SPECIFICATIONS = "UPDATE_PLOT_SPECIFICATIONS";
export const CREATE_NEW_PLOT = "CREATE_NEW_PLOT";
export const CHANGE_ACTIVE_PLOT = "CHANGE_ACTIVE_PLOT";
export const DELETE_PLOT = "DELETE_PLOT";
