export const UPDATE_PLOT_SPECIFICATIONS = "UPDATE_PLOT_SPECIFICATIONS";
export const CREATE_NEW_PLOT = "CREATE_NEW_PLOT";
export const CHANGE_ACTIVE_PLOT = "CHANGE_ACTIVE_PLOT";
export const DELETE_PLOT = "DELETE_PLOT";
export const FETCH_PLOT_DATA = "FETCH_PLOT_DATA";
export const UPDATE_PLOT_DATA = "UPDATE_PLOT_DATA";
export const RESET_PLOT_DATA = "RESET_PLOT_DATA";
export const UPDATE_PLOT_LAYOUT = "UPDATE_PLOT_LAYOUT";
